### ISSUE TITLE
Warmup function times out frequently

### ISSUE THREAD

**Issue by the-bass** [juanjoDiaz/serverless-plugin-warmup#117]
My warmup function errors about 2 times a day with error `Task timed out after 120.08 seconds`. The output in the logs would be

```
START RequestId: 123456789 Version: $LATEST
END RequestId: 123456789
REPORT RequestId: 123456789	Duration: 120083.94 ms	Billed Duration: 120000 ms Memory Size: 128 MB Max Memory Used: 61 MB	
2019-01-30T15:38:08.511Z 123456789 Task timed out after 120.08 seconds
```

So it doesn't even log

```
2019-01-30T15:31:08.716Z	987654321	Warm Up Start
```

as it does on successful invocations. Any idea why this is?

The warmup function is not in a VPC (the functions it calls are, though) and frequency is 5 minutes.

**Comment by juanjoDiaz** [comment]
Hi there,

Interesting...
The first thing that the warmup lambda does is `console.log("Warm Up Start");`. So I can't think of any reason for timing out without even logging that.
On successful runs, it should also log `Warm Up Finished with 0 invoke errors` (or however many errors there were.)

How are you running the lambda outside of a VPC and the function in? Configuring the VPC at the function level? Using a modified version of this plugin? Something else?

Does it always fail at the same time? Any other event happening around that time?
Maybe it fails in the morning when all your lambdas are cold because it actually takes longer to start?

2 minutes might be a bit too short for cold lambdas to start since this plugin waits for the lambda to actually respond. Maybe you just need to increase a bit the timeout? Or maybe we should include an option to not wait for the response?

Do you have a shortcut in your lambdas to respond immediately if the request is coming from the warmup plugin?

**Comment by juanjoDiaz** [comment]
Hi @the-bass,

did you find anything else about this?

**Comment by the-bass** [comment]
> The first thing that the warmup lambda does is `console.log("Warm Up Start");`. So I can't think of any reason for timing out without even logging that.

Yeah, I don't see anything obvious in the code above `console.log("Warm Up Start");` either, but the message indeed isn't being logged.

> On successful runs, it should also log `Warm Up Finished with 0 invoke errors` (or however many errors there were.)

It does so after successful runs for me as well.

> How are you running the lambda outside of a VPC and the function in? Configuring the VPC at the function level? Using a modified version of this plugin? Something else?

I moved the VPC config to the function definitions of functions that actually require it.

> Does it always fail at the same time? Any other event happening around that time?

No, I can't recognise a pattern.

> Maybe it fails in the morning when all your lambdas are cold because it actually takes longer to start?

> 2 minutes might be a bit too short for cold lambdas to start since this plugin waits for the lambda to actually respond. Maybe you just need to increase a bit the timeout?

> Do you have a shortcut in your lambdas to respond immediately if the request is coming from the warmup plugin?

That shouldn't be the problem since `Warm Up Start` isn't even being logged, so it doesn't even get to the point where it pings my functions, right? But, yes, I do have a shortcut.

> Or maybe we should include an option to not wait for the response?

This doesn't seem to be related to this problem, but, if you ask me, I think that would be a good idea! Would save execution time, after all.

**Comment by fschaeffler** [comment]
We're seeing the same issues with the timeout. We just deployed the latest version 4.3.3-rc.1, but still are experiencing the timeouts.

```
START RequestId: b4b2d5ec-a1a4-4a7a-b1b1-c675caceff5f Version: $LATEST
2019-02-13T11:27:33.092Z	b4b2d5ec-a1a4-4a7a-b1b1-c675caceff5f	serverless-plugin-warmup
REPORT RequestId: b4b2d5ec-a1a4-4a7a-b1b1-c675caceff5f	Duration: 6006.18 ms	Billed Duration: 6000 ms 	Memory Size: 1024 MB	Max Memory Used: 54 MB	
2019-02-13T11:27:39.096Z b4b2d5ec-a1a4-4a7a-b1b1-c675caceff5f Task timed out after 6.01 seconds
```

**Comment by the-bass** [comment]
@fschaeffler are the lambdas you are keeping warm in a VPC? Just trying to find out if it's related to the VPC.

**Comment by fschaeffler** [comment]
@the-bass the warmup-lambda, as well as the to be warmed-up lambda are both in no VPC. Please let me know if you need more details on the setup.

**Comment by juanjoDiaz** [comment]
I have deployments with everything under VPC but can't reproduce the same problem...

Some googling show a lot of "lambda random timeout" cases...
For example, https://forums.aws.amazon.com/thread.jspa?messageID=887584&tstart=0

**Comment by juanjoDiaz** [comment]
Did anyone make any progress on this?

**Comment by ptrhck** [comment]
I am also facing this issue, even setting a timeout to 180 seconds. My lambda is deployed to a VPC, so is the warmup function.

**Comment by juanjoDiaz** [comment]
Hi @ptrhck ,

How many lambdas are you warming up?
What do the logs say?
Are some lambdas warmed up before timing up?
Or is there no logs at all like the original post mentioned?

**Comment by ptrhck** [comment]
1. Only one lambda
2. Exactly the same as above, but its reapeating every 3 minutes or so
3. Nothing warmed up yet

**Comment by juanjoDiaz** [comment]
I still haven't been able to reproduce the issue.

Can some of you raise a ticket to AWS support and see if they can tell why the Lambda times out without executing anything?

**Comment by selected-pixel-jameson** [comment]
I'm also seeing the same issue. I have the VPC settings in the provider and they are showing up in the AWS console correctly. But the lambda just times out after 10.01 seconds. I'm using the http-serverless plugin.

```
const handler = serverless(app)
module.exports.handler = async (event, context) => {
  if (event.source === 'serverless-plugin-warmup') {
    console.log('WarmUp - Lambda is warm!')
    return 'Lambda is warm!'
  }

  // you can do other things here
  const result = await handler(event, context)
  // and here
  return result
}

```

**Comment by juanjoDiaz** [comment]
Hi @selected-pixel-jameson ,

That seems a bit different than what others are experiencing.
Other users don't see any log at all and the function times out.
You actually see logs and even one function being warmed up.

Is function `xxxxxxxx` returning early as expected?
It seems like `xxxxxxxx` never responds so the function just stays forever waiting.
Can you check in function `xxxxxxxx` logs if `'WarmUp - Lambda is warm!'` is logged and the function returned right after?

**Comment by juanjoDiaz** [comment]
Is this still a problem for anyone?
Has anyone been able to replicate the issue?

**Comment by sav-valerio** [comment]
I think that the problem is still there, everything just time outs for me.
Already tried increasing the timeout value.

```
07:30:37 START RequestId: 4bea07a9-435f-4904-9197-133f789f5db6 Version: $LATEST

07:30:37 2019-09-25T07:30:37.720Z 4bea07a9-435f-4904-9197-133f789f5db6 INFO Warm Up Start

07:30:37 2019-09-25T07:30:37.737Z 4bea07a9-435f-4904-9197-133f789f5db6 INFO Warming up function: lambda-authorizer-dev-welcome with concurrency: 1

07:30:37 2019-09-25T07:30:37.958Z 4bea07a9-435f-4904-9197-133f789f5db6 INFO Warming up function: lambda-authorizer-dev-authorize with concurrency: 1

07:31:17 END RequestId: 4bea07a9-435f-4904-9197-133f789f5db6

07:31:17 REPORT RequestId: 4bea07a9-435f-4904-9197-133f789f5db6 Duration: 40040.17 ms Billed Duration: 40000 ms Memory Size: 256 MB Max Memory Used: 37 MB Init Duration: 438.15 ms
```

*serverless.yml*:
```
custom:
  warmup:
    enabled: true
    memorySize: 256
    events:
      - schedule: rate(10 minutes)
    timeout: 40
    prewarm: true
```

**Comment by stanyq4** [comment]
Yes, this is still a problem. Occasionally getting: `Task timed out after 10.01 seconds`
Warming up 5 lambdas concurrently, no VPC.

**Comment by juanjoDiaz** [comment]
That's odd, @stanyq4.
Have you raised a ticket to AWS about it as I suggested above?
Could you provide a small project so I could replicate the issue?

**Comment by stanyq4** [comment]
Hi @juanjoDiaz 
I haven't logged any tickets with AWS yet. 
With the sample project - it's a bit tricky, it's a very basic setup where `serverless-plugin-warmup` triggers 4 lambdas which `return` right away. The issue occurs very rarely, once a day or once in a few days.

**Comment by juanjoDiaz** [comment]
That's why I think that the ticket should be submitted to AWS. Because it seems to be an intermittent issue that happens for no apparent cause.

**Comment by stanyq4** [comment]
I agree, it sounds like something is going on with containers, they are not finishing the execution properly.

The only reason why I addressed it with you guys, is because we run lambdas very heavily in our environment and those lambdas that don't utilize `serverless-plugin-warmup` and run even at a higher rate - don't have this issue.

**Comment by CoderickLamar** [comment]
Did anyone make progress on this? I don't use this lib, but I have other very basic lambda functions that experience this exact same issue. 

It does not log anything (even a basic "function is starting" log), and times out.

**Comment by praneetrattan** [comment]
> That's why I think that the ticket should be submitted to AWS. Because it seems to be an intermittent issue that happens for no apparent cause.
We have been facing the same issue. Raised a ticket with AWS with no avail. However, these timeout issues are not limited to just warming up lambdas. I have seen intermittent timeouts on normal execution lambdas too. And this started happening around feb. We had existing code in prod, and with no changes it started timing out. 
Of late even warm-up lambdas timeout after 10 seconds, and this happens for about 8-10 minutes, and then resumes normal function.
Still waiting on AWS to respond to it...

**Comment by idhard** [comment]
@praneetrattan we are facing similar issue in our app , without any change in the code timeouts started being a problem , did you get an answer from AWS support ? thanks

**Comment by praneetrattan** [comment]
@idhard Nope, they say they are still investigating. It seems to be a recurring problem.

**Comment by praneetrattan** [comment]
@idhard
I spoke with AWS and they said this could not be a container issue, because if it was we would not see last cloudwatch logs which mention END and REPORT sections. That logging only happens when the container gets the end of request or timeout is reached. They said that it seems that the lambda is stuck waiting for some event to finish, and when that doesn't happen, it times out.

@juanjoDiaz My code for warm up is:
```
if (event.source === 'serverless-plugin-warmup') {
        return context.functionName + ' - warmed up!';
    }
```
Once the return statement happens, is there anything that the warmup plugin does that might initiate a http call? any db request, within aws resources, or anything else that is not simple linear code execution?
Because if I look at my logs, the warmup actually does happen, but I see the timeout on the main warmup lambda which lists all records: (as below)

The `integration-staging-warmup-plugin` cloudwatch log shows a timeout for `crmNotifyVendor`:
<img width="1607" alt="Screen Shot 2020-10-15 at 4 22 57 AM" src="https://user-images.githubusercontent.com/5843603/96096938-62320900-0e9e-11eb-808f-78f3640c836a.png">

However, for the exact same timestamp, the actual function `integration-staging-crmNotifyVendor` cloudwatch shows a successful invocation:
<img width="1612" alt="Screen Shot 2020-10-15 at 4 23 20 AM" src="https://user-images.githubusercontent.com/5843603/96097104-93aad480-0e9e-11eb-8697-9129bd4c1168.png">

Could it be that the lambda is stuck waiting for the successful invocation response or some other subsequent event, even though the invocation was successful and done?

**Comment by juanjoDiaz** [comment]
Your case seems different @praneetrattan your lambda does log the invocations but doesn't seem to have time to wait for all the responses.

The issue listed here by other people was that the warmup lambda was not logging anything at all.

**Comment by samrith-s** [comment]
I have this same error. Also, though I have not set up the `event` parameter, my warmup plugin gets invoked every minute (!!)

And each minute, they get timed out.

Here is my warmup config:
```yaml
custom:
    warmup:
        prewarm: true
        package:
            individually: true
```

![image](https://user-images.githubusercontent.com/9032162/104301699-3d165c00-54c8-11eb-8734-e587e568acca.png)

**Comment by juanjoDiaz** [comment]
Hi @samrith-s ,

That's odd...
The default event should be every 5 minutes instead of 1.

Other than that, the issue is could be network-related as documented in the readme.
If you are deploying to a private subnet within a VPC you need to set up a NAT or set the warmer outside of the VPC.

**Comment by juanjoDiaz** [comment]
It's been 2 years since this was raised.
There has been a few issues commented here but none of them seemed to be related to the plugin itself.
The latest release v5.0.0 includes a connection timeout to avoid the warmer hanging and timing out on networking issues, a default role to avoid permissions issues, and other features targeting misconfigurations and user errors.

So I'll go ahead and close this issue.
Feel free to reopen it if you think that there is still something to be fixed in this plugin.

**Comment by alanmun** [comment]
Was there ever an established solution for warmers erroring out due to timeouts but likely the cause was cold starts and waiting to hear back from the lambdas being warmed? Because I get errors like:

INFO Warming up function: A with concurrency 3
INFO Warming up function: B with concurrency 3
INFO Warming up function: C with concurrency 2
Warm up Invoke Success: A
END
REPORT Duration 10000.00 ms Max Memory Used 91MB Status: timeout

These make me think that the warmer wouldn't be erroring if it did a fire and forget kind of approach, and that the timeouts are happening because of cold starts taking too long to get responses back to the warmer. I know that my cold starts are especially awful because I use unzipping as part of my lambda inits and that makes them ~9s in the worst case.

Though, i'm not sure if fire and forget is an ideal solution or not, its just what jumps out to me as an approach to take when lambdas take so long to respond back to a warmer
