### ISSUE TITLE
Travis builds have stopped working

### ISSUE THREAD

**Issue by juanjoDiaz** [juanjoDiaz/serverless-plugin-warmup#224]
Since my admin permissions were removed and added back, it seems that Travis builds don't notify GitHub any more.
I tried to investigate but Travis doesn't let me see the setting since I don't have enough permissions. Based on this, I might need some extra permissions because of the repo being part of an org.

I also considered moving GitHub actions since it's significantly faster than Travis. However, I'd need to put my NPM publishing token in the settings, and Fidel admins would be able to see it which is obviously not OK since NPM tokens are not per-repo but allows you to publish anything.

So, either I can get the needed permissions within the Fidel org or Fidel could transfer me the repository ownership (in GitHub and NPM).
I think that, considering that Fidel hasn't been involved in this since forever, transfer the repo would be the easiest and best way. Of course, the repo's history will still be there and I can even add an acknowledgement to the readme thanking Fidel for its original contribution.

Please, let me know what you think.
Tagging the usual suspects: @goncaloneves and @diogogvhenriques

**Comment by diogogvhenriques** [comment]
Really appreciate all the work you have been doing to maintain this repository. 

I've forward this issue internally, we will try to get back to you on the following days.

**Comment by diogogvhenriques** [comment]
@juanjoDiaz Spoke with the team internally and we all agreed that you have been doing a great work maintain this package that started at Fidel.

Since, like you pointed out, we haven't been much involve in this package, it makes sense that you have complete ownership on it, we also tried to set the correct permissions so that you have the freedom to maintain this repository without issues. But since we have been doing more cleaning on the tools we are using on GitHub, issues like this one might occur more often. It does not make sense for you to be affected by our changes, therefore we agree that you should transfer the repository.

We really appreciate you maintaining repo's history and the acknowledgement to the readme thanking Fidel 🙏  
Fidel started this package from necessity on an issue we had and we wanted to share this with the community since we thought this could be affecting more people. Continuing to see this package being improved gives us great joy and the last thing we want is this repository to be abandon or cause trouble to the current maintainer that is doing a great work on it.

@juanjoDiaz Let us know if there's anything you need from us.

**Comment by juanjoDiaz** [comment]
Thanks @diogogvhenriques for taking care of this!
