### ISSUE TITLE
ServerlessError because role name of warmer is too long

### ISSUE THREAD

**Issue by holyachon** [juanjoDiaz/serverless-plugin-warmup#280]
Error message : 
```
 ServerlessError: An error occurred: WarmUpPluginWarmerRole - 1 validation error detected: Value 'serverless-ssl-certificate-manager-prod-ap-northeast-1-warmer-role' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: c826ba3b-d4da-4562-b995-4466635978e6; Proxy: null).
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:94:23
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I think user can't change role name which is generated by plugin.
How about add roleName option and set default value to `{service.service}-{stage}-{aws:region}-{warmerName.toLowerCase()}-role?`

associated code(probably) : https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/cff619dc16c5970d278b6987bf6bd309e3917ec7/src/warmer.js#L30-L37

**Comment by juanjoDiaz** [comment]
If you provide a string to `role` it will try to use that role. So it should exist or be declared in the resource section.

Allow the default role but set the name with a `roleName` is a bit odd API in my opinion.

Your service name is just very long and will probably cause problems because of that. If not with this plugin, with something else.
I'd advise that you simply rename the service to `sls-ssl-certificate-mgr` or something shorter and mare manageable.

**Comment by juanjoDiaz** [comment]
Closing this since it won't be implemented.
As advised, I think that the service name was just too long 🙂

**Comment by holyachon** [comment]
Sorry for late reply. Thank you :)
