### ISSUE TITLE
6.1.0 not available at npmjs.com

### ISSUE THREAD

**Issue by Pinny3** [juanjoDiaz/serverless-plugin-warmup#294]
Hi there,

first of all thanks for your great work. 

We need the re movement of the layers you provided in version 6.1.0.

Unfortunately I do not see any version 6.1.0 currently at npmjs.com at

https://www.npmjs.com/package/serverless-plugin-warmup

So, when will it be available at npmjs.com?

**Comment by juanjoDiaz** [comment]
Hi @Pinny3 ,

This is due to #218.
Fidel, the company that started this project still own the NPM repo and they've remove my rights to publish new versions.

I'll wait until the holidays are over.
If I haven't got a response I'll contact NPM. But If I can't get access to the package, I'll have to publish under a new name.

**Comment by juanjoDiaz** [comment]
Problem solved and 6.1.0 published!
