### ISSUE TITLE
Mismatching between required Serverless 3.8(from the latest v8 release) and the latest Serverless v3.22 

### ISSUE THREAD

**Issue by terret** [juanjoDiaz/serverless-plugin-warmup#319]
In the last published release of the `serverless-plugin-warmap` there is a description

> Only support `Serverless` v3.8 or higher

<img width="948" alt="image" src="https://user-images.githubusercontent.com/46281023/185891351-e2e33e29-33aa-4052-9bce-1692cb7b134f.png">

But the latest published `serverless` [version is 3.22](https://github.com/serverless/serverless/releases)

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/46281023/185891523-44a8683b-5552-4e3f-9f6f-0eed00d644cb.png">

Is it a typo or did I miss something?

**Comment by arkD** [comment]
'3.8 or higher' includes 3.22

**Comment by juanjoDiaz** [comment]
Hi guys,

There is a Serverless 3.8 (See https://github.com/serverless/serverless/releases/tag/v3.8.0).
Then there is another bunch of newer release.

@arkD is right. The requirement is any version above 3.8.
This is due to the `Support logRetentionInDays per function` change which was introduced there.

**Comment by terret** [comment]
@juanjoDiaz Thanks for your response!
